-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 20:30:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `locadora` ;

-- -----------------------------------------------------
-- Table `locadora`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`cliente` (
  `clienteId` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`clienteId`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `locadora`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`pedido` (
  `pedidoId` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `clienteId` SMALLINT(6) NOT NULL,
  `valorTotal` FLOAT NULL,
  `dataPedido` VARCHAR(30) NULL,
  `dataEntrega` VARCHAR(30) NULL,
  `situacao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`pedidoId`),
  INDEX `clienteId` (`clienteId` ASC),
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`clienteId`)
    REFERENCES `locadora`.`cliente` (`clienteId`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `locadora`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`filme` (
  `filmeId` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`filmeId`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `locadora`.`alocacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`alocacao` (
  `alocacaoId` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `pedidoId` SMALLINT(6) NOT NULL,
  `filmeId` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`alocacaoId`),
  INDEX `pedidoId` (`pedidoId` ASC),
  INDEX `filmeId` (`filmeId` ASC),
  CONSTRAINT `alocacao_ibfk_1`
    FOREIGN KEY (`pedidoId`)
    REFERENCES `locadora`.`pedido` (`pedidoId`),
  CONSTRAINT `alocacao_ibfk_2`
    FOREIGN KEY (`filmeId`)
    REFERENCES `locadora`.`filme` (`filmeId`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
